### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Maryam0330**
## Checklist

- [ ] I have read and followed the [contribution guidelines](CONTRIBUTING.md).
- [ ] I have tested my changes.
- [ ] My code follows the project's coding standards.

### CODE REVIEW

**Comment by Munsif-Raza-T** [comment]
Can you please add the dataset that you have used into the Dataset folder.

**Comment by Maryam0330** [comment]
Okay. I will add the datasets that i have used in this folder. Should i add the datasets in Data Analysis folder?

**Comment by Maryam0330** [comment]
Or should i add it in dataset folder?

**Comment by Munsif-Raza-T** [comment]
No for dataset there is a separate folder named Dataset in Projects

**Comment by Munsif-Raza-T** [comment]
> Or should i add it in dataset folder?

Yes in Dataset folder

**Comment by Maryam0330** [comment]
Okay. I have used 3 datasets in this repository, so i am adding all of the 3 datasets.

**Comment by Maryam0330** [comment]
Now, i observed that from 3 datasets that i have used. One dataset 'Mall_customers.csv' is already in the dataset folder. So in order to avoid duplication i will upload other 2 datasets.

**Comment by Munsif-Raza-T** [comment]
Congratulations your PR is merged. And Hacktoberfest approved

**Comment by Munsif-Raza-T** [comment]
Do share this repo with your circle

**Comment by Maryam0330** [comment]
Thank you so much. Had a great experience in contributing.

**Pull request merged**
