### PR TITLE
Add My Machine Learning Projects

### PR DESCRIPTION
**Pull request by Faiznurullah**
Please Merge And Give Me Label Hacktoberfest-Accepted Thanks You Guys

### CODE REVIEW

**Comment by Faiznurullah** [comment]
Give me label hacktoberfest-accepted please

**Comment by Faiznurullah** [comment]
I am very grateful to you for the merge, now please give a label for this Pull Request hacktoberfest-accepted

**Comment by Munsif-Raza-T** [comment]
Sure I shall label it soon. I'm on my smartphone for now, whenever I get on my laptop I shall.
Thank you for contributing✨

**Comment by Munsif-Raza-T** [comment]
Furthermore, if you share this repo with your circle it will be great.

**Comment by Munsif-Raza-T** [comment]
Labeled as Hacktoberfest-approved

**Pull request merged**
